# Generated by Django 5.2.10 on 2026-02-03 23:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Figura",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=100)),
                ("medida", models.CharField(help_text="Ej: 40cm", max_length=50)),
                (
                    "material",
                    models.CharField(
                        choices=[("RESINA", "Resina"), ("VIDRIO", "Vidrio/Fibra")],
                        default="RESINA",
                        max_length=20,
                    ),
                ),
                ("precio", models.DecimalField(decimal_places=2, max_digits=10)),
                ("stock", models.IntegerField(default=0)),
                (
                    "imagen_url",
                    models.URLField(
                        blank=True, help_text="Link de la foto de la figura", null=True
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Venta",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("cliente", models.CharField(max_length=150)),
                ("fecha_venta", models.DateTimeField(auto_now_add=True)),
                ("monto_total", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "estado",
                    models.CharField(
                        choices=[("PAGADO", "Pagado"), ("PENDIENTE", "Pendiente")],
                        default="PENDIENTE",
                        max_length=20,
                    ),
                ),
                (
                    "figura",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="core.figura"
                    ),
                ),
            ],
        ),
    ]
