# Generated by Django 5.2.10 on 2026-02-03 23:30

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="venta",
            name="monto_total",
        ),
        migrations.AddField(
            model_name="venta",
            name="deuda_total",
            field=models.DecimalField(decimal_places=2, default=120.0, max_digits=10),
        ),
        migrations.AddField(
            model_name="venta",
            name="fecha_limite",
            field=models.DateField(
                default=django.utils.timezone.now,
                help_text="Día máximo para el abono del mes",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="venta",
            name="monto_pagado",
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AlterField(
            model_name="venta",
            name="estado",
            field=models.CharField(
                choices=[
                    ("PAGADO", "Pagado Totalmente"),
                    ("PENDIENTE", "Pendiente de Pago"),
                    ("CANCELADO_MES", "Cancelado este Mes"),
                ],
                default="PENDIENTE",
                max_length=20,
            ),
        ),
    ]
