# Generated by Django 5.2.10 on 2026-02-04 00:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_remove_venta_monto_total_venta_deuda_total_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="figura",
            name="descripcion",
            field=models.CharField(
                default="Artesanía Sacra - Calidad Premium", max_length=200
            ),
        ),
    ]
