# Generated by Django 5.2.10 on 2026-02-04 00:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0003_figura_descripcion"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="figura",
            name="imagen_url",
        ),
        migrations.AddField(
            model_name="figura",
            name="imagen",
            field=models.ImageField(
                blank=True,
                help_text="Sube la foto de la figura",
                null=True,
                upload_to="figuras/",
            ),
        ),
    ]
