# Generated by Django 5.2.10 on 2026-02-04 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0004_remove_figura_imagen_url_figura_imagen"),
    ]

    operations = [
        migrations.AddField(
            model_name="venta",
            name="archivo_contrato",
            field=models.FileField(
                blank=True,
                help_text="PDF o Imagen del contrato/firma",
                null=True,
                upload_to="contratos/",
            ),
        ),
        migrations.AddField(
            model_name="venta",
            name="cedula",
            field=models.CharField(
                blank=True, max_length=20, null=True, verbose_name="Cédula/RUC"
            ),
        ),
        migrations.AddField(
            model_name="venta",
            name="domicilio",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="venta",
            name="modalidad_pago",
            field=models.CharField(
                choices=[
                    ("presencial", "Cobro Presencial (Domicilio)"),
                    ("virtual", "Transferencia Virtual"),
                    ("contado", "Venta de Contado"),
                ],
                default="presencial",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="venta",
            name="n_contrato",
            field=models.CharField(
                blank=True,
                max_length=50,
                null=True,
                unique=True,
                verbose_name="N° de Contrato",
            ),
        ),
        migrations.AddField(
            model_name="venta",
            name="referencia",
            field=models.CharField(
                blank=True,
                help_text="Ej: Junto a la escuela",
                max_length=255,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="venta",
            name="telefono",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name="venta",
            name="deuda_total",
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
