# Generated by Django 5.2.10 on 2026-02-04 21:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0005_venta_archivo_contrato_venta_cedula_venta_domicilio_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="venta",
            name="vendedor",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="figura",
            name="descripcion",
            field=models.TextField(
                blank=True,
                default="Artesanía Sacra - Calidad Premium",
                max_length=500,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="venta",
            name="archivo_contrato",
            field=models.FileField(blank=True, null=True, upload_to="contratos/"),
        ),
        migrations.AlterField(
            model_name="venta",
            name="referencia",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.CreateModel(
            name="Abono",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("monto", models.DecimalField(decimal_places=2, max_digits=10)),
                ("fecha_pago", models.DateTimeField(auto_now_add=True)),
                (
                    "comprobante",
                    models.ImageField(blank=True, null=True, upload_to="abonos/"),
                ),
                (
                    "notas",
                    models.CharField(
                        blank=True,
                        help_text="Ej: Pago en efectivo",
                        max_length=255,
                        null=True,
                    ),
                ),
                (
                    "venta",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="abonos",
                        to="core.venta",
                    ),
                ),
            ],
        ),
    ]
