# Generated by Django 5.2.10 on 2026-02-07 02:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0006_venta_vendedor_alter_figura_descripcion_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Carrito",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("cantidad", models.PositiveIntegerField(default=1)),
                ("agregado_el", models.DateTimeField(auto_now_add=True)),
                (
                    "figura",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="core.figura"
                    ),
                ),
                (
                    "usuario",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="carrito",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
