# Generated by Django 5.2.10 on 2026-02-07 03:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0008_perfil"),
    ]

    operations = [
        migrations.CreateModel(
            name="CajaChica",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "saldo",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=12),
                ),
                ("ultima_actualizacion", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Caja Chica",
                "verbose_name_plural": "Caja Chica",
            },
        ),
        migrations.AddField(
            model_name="figura",
            name="precio_costo",
            field=models.DecimalField(
                decimal_places=2,
                default=0.0,
                max_digits=10,
                verbose_name="Precio de Costo (Proveedor)",
            ),
        ),
        migrations.AlterField(
            model_name="figura",
            name="precio",
            field=models.DecimalField(
                decimal_places=2, max_digits=10, verbose_name="Precio de Venta"
            ),
        ),
    ]
