# Generated by Django 5.2.10 on 2026-02-07 04:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0009_cajachica_figura_precio_costo_alter_figura_precio"),
    ]

    operations = [
        migrations.AlterField(
            model_name="figura",
            name="precio",
            field=models.DecimalField(
                decimal_places=2,
                max_digits=10,
                verbose_name="Precio de Venta (Cliente)",
            ),
        ),
    ]
